steps:
- name: "gcr.io/cloud-builders/git"
  args: ["clone", "https://github.com/ParadigmFoundation/ParadigmCore", "./pcsrc"]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'gcr.io/paradigmcore/paradigmcore:base-$SHORT_SHA',
    '-f',
    './pcrsc/docker/Dockerfile',
    './pcsrc'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'gcr.io/paradigmcore/paradigmcore:testnet-$SHORT_SHA',
    '-f',
    './pcsrc/docker/Testnet.Dockerfile',
    './pcsrc'
  ]
images: ['gcr.io/paradigmcore/paradigmcore:base-$SHORT_SHA', 'gcr.io/paradigmcore/paradigmcore:testnet-$SHORT_SHA']