steps:
- name: "gcr.io/cloud-builders/git"
  args: ["clone", "-b", "$BRANCH_NAME", "https://github.com/ParadigmFoundation/ParadigmCore", "./pcsrc"]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'gcr.io/paradigmcore/base:$BRANCH_NAME-$SHORT_SHA',
    '-f',
    './pcsrc/docker/Dockerfile',
    './pcsrc'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'gcr.io/paradigmcore/testnet:$BRANCH_NAME-$SHORT_SHA',
    '-f',
    './pcsrc/docker/Testnet.Dockerfile',
    './pcsrc'
  ]
- name: "gcr.io/cloud-builders/docker"
  args: [
    "tag",
    'gcr.io/paradigmcore/testnet:$BRANCH_NAME-$SHORT_SHA',
    'gcr.io/paradigmcore/testnet:latest',
  ]
- name: "gcr.io/cloud-builders/docker"
  args: [
    "tag",
    'gcr.io/paradigmcore/base:$BRANCH_NAME-$SHORT_SHA',
    'gcr.io/paradigmcore/base:latest',
  ]
images: [
  'gcr.io/paradigmcore/base:$BRANCH_NAME-$SHORT_SHA',
  'gcr.io/paradigmcore/testnet:$BRANCH_NAME-$SHORT_SHA',
  'gcr.io/paradigmcore/base:latest',
  'gcr.io/paradigmcore/testnet:latest'
]