steps:
- name: 'ubuntu'
  args: ['ls', '-la']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'gcr.io/paradigmcore/paradigmcore:base-$SHORT_SHA',
    '-f ./docker/Dockerfile',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'gcr.io/paradigmcore/paradigmcore:testnet-$SHORT_SHA',
    '-f ./docker/Testnet.Dockerfile',
    '.'
  ]
images: ['gcr.io/paradigmcore/paradigmcore:base-$SHORT_SHA', 'gcr.io/paradigmcore/paradigmcore:testnet-$SHORT_SHA']